/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface CloudflareEnv cloudflare-env.d.ts` (hash: be983da815b6592ccc42fed6c0a564de)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./custom-worker");
	}
	interface Env {
		EDGE_WRITE_RATE_LIMITER: RateLimit;
		ASSETS: Fetcher;
		APP_URL: "https://bidstage.app";
		PAYMENT_PROVIDER: "creem";
		CREEM_TEST_MODE: "false";
		WORKER_SELF_REFERENCE: Service<typeof import("./custom-worker").default>;
	}
}
interface CloudflareEnv extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_URL" | "PAYMENT_PROVIDER" | "CREEM_TEST_MODE">> {}
}
