/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface CloudflareEnv cloudflare-env.d.ts` (hash: fa3372a34d8bdce9f29d3980265db57f)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./custom-worker");
	}
	interface Env {
		HYPERDRIVE: Hyperdrive;
		EDGE_WRITE_RATE_LIMITER: RateLimit;
		ASSETS: Fetcher;
		APP_URL: "https://bidstage.app";
		PAYMENT_PROVIDER: "creem";
		CREEM_TEST_MODE: "false";
		TURNSTILE_SITE_KEY: "0x4AAAAAAEZg5FPIO9JvkcXu";
		CREEM_API_KEY: string;
		CREEM_WEBHOOK_SECRET: string;
		CREEM_PRODUCT_ID: string;
		TURNSTILE_SECRET_KEY: string;
		FOUNDER_ACCESS_SECRET: string;
		GITHUB_CLIENT_ID: string;
		GITHUB_CLIENT_SECRET: string;
		GITHUB_API_TOKEN: string;
		RATE_LIMIT_SALT: string;
		MAINTENANCE_SECRET: string;
		WORKER_SELF_REFERENCE: Service<typeof import("./custom-worker").default>;
	}
}
interface CloudflareEnv extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_URL" | "PAYMENT_PROVIDER" | "CREEM_TEST_MODE" | "TURNSTILE_SITE_KEY" | "CREEM_API_KEY" | "CREEM_WEBHOOK_SECRET" | "CREEM_PRODUCT_ID" | "TURNSTILE_SECRET_KEY" | "FOUNDER_ACCESS_SECRET" | "GITHUB_CLIENT_ID" | "GITHUB_CLIENT_SECRET" | "GITHUB_API_TOKEN" | "RATE_LIMIT_SALT" | "MAINTENANCE_SECRET">> {}
}
