/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface SupportMailEnv cloudflare-env.d.ts` (hash: 80d94799590e08ae4796e7923d83d492)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env {
		SUPPORT_FORWARD_TO: string;
	}
}
interface SupportMailEnv extends Cloudflare.Env {}
